version: '3.8'

services:
  mongo:
    image: mongo:6.0  # or latest if you prefer
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

volumes:
  mongo-data:
